/**
 * Static grouping for the location dropdowns.
 *
 * `locations` is a flat id list of ~200 rows; the filters need it split into
 * optgroups to be usable. Ids are stable (they are the primary keys seeded in
 * db/seeds/02_locations.sql), so the grouping lives here rather than in a
 * column every deployment would have to backfill. Ids missing from this table
 * fall into the trailing "other" group at render time.
 */
export const LOCATION_GROUPS: { key: string; ids: string[] }[] = [
  { key: "online", ids: ["Online"] },
  {
    key: "kz",
    ids: [
      "Astana",
      "Almaty",
      "Shymkent",
      "Abai_Region",
      "Akmola_Region",
      "Aktobe_Region",
      "Almaty_Region",
      "Atyrau_Region",
      "East_Kazakhstan_Region",
      "Jambyl_Region",
      "Jetisu_Region",
      "Karaganda_Region",
      "Kostanay_Region",
      "Kyzylorda_Region",
      "Mangystau_Region",
      "North_Kazakhstan_Region",
      "Pavlodar_Region",
      "Turkestan_Region",
      "Ulytau_Region",
      "West_Kazakhstan_Region",
      "Semey",
      "Kokshetau",
      "Aktobe",
      "Konayev",
      "Atyrau",
      "Oskemen",
      "Taraz",
      "Taldykorgan",
      "Karaganda",
      "Kostanay",
      "Kyzylorda",
      "Aktau",
      "Petropavl",
      "Pavlodar",
      "Turkistan",
      "Jezkazgan",
      "Oral",
      "Alatau",
      "Temirtau",
      "Zhanaozen",
      "Ekibastuz",
      "Rudny",
      "Kentau",
      "Kaskelen",
      "Arys",
      "Balkhash",
      "Aksu",
      "Satbayev",
      "Kulsary",
      "Talgar",
      "Saryagash",
      "Kosshy",
      "Zharkent",
      "Shu",
      "Zhetisay",
      "Shardara",
      "Zachagansk",
      "Karabulak",
      "Beyneu",
      "Ayteke_Bi",
      "Uzynagash",
      "Mangystau_Locality",
    ],
  },
  {
    key: "kg",
    ids: [
      "Kyrgyzstan",
      "Bishkek",
      "Osh",
      "Chuy_Region",
      "Issyk_Kul_Region",
      "Jalal_Abad_Region",
      "Naryn_Region",
      "Batken_Region",
      "Talas_Region",
      "Osh_Region",
      "Karakol",
      "Naryn_City",
      "Talas_City",
      "Jalal_Abad_City",
      "Batken_City",
      "Kyzyl_Kiya",
      "Balykchy",
      "Uzgen",
      "Kara_Suu",
      "Tokmok",
    ],
  },
  {
    key: "uz",
    ids: [
      "Uzbekistan",
      "Tashkent",
      "Karakalpakstan",
      "Andijan_Region",
      "Bukhara_Region",
      "Fergana_Region",
      "Jizzakh_Region",
      "Khorezm_Region",
      "Namangan_Region",
      "Navoiy_Region",
      "Kashkadarya_Region",
      "Samarkand_Region",
      "Sirdaryo_Region",
      "Surkhandarya_Region",
      "Tashkent_Region",
    ],
  },
  {
    key: "tr",
    ids: [
      "Turkey",
      "Ankara",
      "Istanbul",
      "Izmir",
      "Bursa",
      "Antalya",
      "Adana",
      "Konya",
    ],
  },
  {
    key: "mn",
    ids: [
      "Mongolia",
      "Bayan_Olgii_City",
      "Bayan_Olgii_Province",
      "Ulaanbaatar",
      "Khovd_Province",
    ],
  },
  {
    key: "ru",
    ids: ["Russia", "Moscow", "Saint_Petersburg", "Tatarstan", "Bashkortostan"],
  },
  { key: "cz", ids: ["Czechia", "Prague", "Pardubice"] },
  {
    key: "other",
    ids: [
      "Colombia",
      "Bogota",
      "Cali",
      "South_Korea",
      "Seoul",
      "USA",
      "UK",
      "France",
      "Spain",
      "Italy",
      "Brazil",
      "Argentina",
      "Antigua_and_Barbuda",
      "Poland",
      "Latvia",
      "Hungary",
      "Romania",
      "Ukraine",
      "Bulgaria",
      "Georgia",
      "Turkmenistan",
      "UAE",
      "Qatar",
      "India",
      "Pakistan",
      "China",
      "Bangladesh",
      "Sri_Lanka",
      "Uganda",
      "Zambia",
      "Nigeria",
      "Benin",
      "Ghana",
      "Ivory_Coast",
    ],
  },
  {
    key: "world",
    ids: [
      "Caribbean",
      "Central_America",
      "South_America",
      "North_America",
      "Europe",
      "West_Africa",
      "Africa",
      "Middle_East",
      "South_Asia",
      "Southeast_Asia",
      "Oceania",
      "East_Asia",
      "Central_Asia",
    ],
  },
];
